title: Christopher Perng
logo: /image/headshot_circle.png
description: >
  Data Analyst | Data Scientist
  University of Texas at Austin
  Operations Research Industrial Engineering
show_downloads: true
theme: jekyll-theme-minimal
