title: Christopher Perng
logo: /image/headshot_circle.png
description: >
  University of Texas at Austin <br>
  Operations Research Industrial Engineering
show_downloads: true
theme: jekyll-theme-minimal
